### ISSUE TITLE
Exception getting block type in world - ExtraUtilites

### ISSUE THREAD

**Issue by Tsyklop** [CreativeMD/World-Generation-Manager#2]
Crash - http://pastebin.com/AzG8NTpp

Config file: http://pastebin.com/c2kJFj4c

EDIT
I remove ExtraUtilites and all OK. But i need ExtraUtilites...Fix Pls

**Comment by CreativeMD** [comment]
Same here, could you send me all your mods?

**Comment by Tsyklop** [comment]
@CreativeMD http://pastebin.com/tHAcrPje

**Comment by CreativeMD** [comment]
Should be fixed in 0.4.4
