### ISSUE TITLE
Railcraft Ores isn't gen

### ISSUE THREAD

**Issue by RafaelPNV** [CreativeMD/World-Generation-Manager#5]
Hello, Could you help me? I`m using railcraft and I don`t find any ore, so I try world gen, but all ores like the electrical age, IC2, etc was gen only Railcraft's ores wasn't. Is there a way to add railcraft to gen the ores?

**Comment by CreativeMD** [comment]
Sorry, but RailCraft has a weird behavior is not supported by my mod :(
